### ISSUE TITLE
Issue when getting logs

### ISSUE THREAD

**Issue by farfeduc** [adambaumeister/goflow#25]
Hi,

I have the following messages when receiving flows, any idea ? 
```bash
panic: runtime error: slice bounds out of range [:9591] with capacity 1500

goroutine 20 [running]:
github.com/adambaumeister/goflow/frontends.Route(0xa00000000, 0x9b1bc5e3adb3b, 0x100008400000003, 0x4f0, 0xc000142c00, 0x0, 0x0, 0x0, 0xc000224000, 0x5dc, ...)
	/go/src/github.com/adambaumeister/goflow/frontends/netflow.go:257 +0x5bb
github.com/adambaumeister/goflow/frontends.Netflow.Start(0xc000142c00, 0xc0000a6c60, 0x10, 0x10, 0x270f, 0xaf14a0, 0xc00010a180)
	/go/src/github.com/adambaumeister/goflow/frontends/netflow.go:343 +0x3b5
created by main.main
	/go/src/app/goflow.go:26 +0x1ba
```

**Comment by adambaumeister** [comment]
Hiya,

What is your environment setup? hardware/vendor/netflow configuration? Are you using jumbo frames?

**Comment by farfeduc** [comment]
I have a Sophos UTM send netflows in IPFIX to my mac where I have a goflow container. Whenever I receive a flow, I get this error.

**Comment by dmgeurts** [comment]
Was this issue resolved or should IPFIX not be used?
